# Generated by Django 3.1.1 on 2020-10-29 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_mine', models.IntegerField(default=0, null=True)),
                ('crystal_mine', models.IntegerField(default=0, null=True)),
                ('deuterium_mine', models.IntegerField(default=0, null=True)),
                ('solar_plant', models.IntegerField(default=0, null=True)),
                ('fusion_plant', models.IntegerField(default=0, null=True)),
                ('metal_storage', models.IntegerField(default=0, null=True)),
                ('crystal_storage', models.IntegerField(default=0, null=True)),
                ('deuterium_storage', models.IntegerField(default=0, null=True)),
                ('robotics_factory', models.IntegerField(default=0, null=True)),
                ('shipyard', models.IntegerField(default=0, null=True)),
                ('research_laboratory', models.IntegerField(default=0, null=True)),
                ('alliance_depot', models.IntegerField(default=0, null=True)),
                ('missile_silo', models.IntegerField(default=0, null=True)),
                ('nanite_factory', models.IntegerField(default=0, null=True)),
                ('terraformer', models.IntegerField(default=0, null=True)),
                ('repair_dock', models.IntegerField(default=0, null=True)),
                ('moon_base', models.IntegerField(default=0, null=True)),
                ('sensor_phalanx', models.IntegerField(default=0, null=True)),
                ('jump_gate', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Defences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocket_launcher', models.IntegerField(default=0, null=True)),
                ('laser_cannon_light', models.IntegerField(default=0, null=True)),
                ('laser_cannon_heavy', models.IntegerField(default=0, null=True)),
                ('gauss_cannon', models.IntegerField(default=0, null=True)),
                ('ion_cannon', models.IntegerField(default=0, null=True)),
                ('plasma_cannon', models.IntegerField(default=0, null=True)),
                ('shield_dome_small', models.IntegerField(default=0, null=True)),
                ('shield_dome_large', models.IntegerField(default=0, null=True)),
                ('missile_interceptor', models.IntegerField(default=0, null=True)),
                ('missile_interplanetary', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_transporter', models.IntegerField(default=0, null=True)),
                ('large_transporter', models.IntegerField(default=0, null=True)),
                ('colonyShip', models.IntegerField(default=0, null=True)),
                ('recycler', models.IntegerField(default=0, null=True)),
                ('light_fighter', models.IntegerField(default=0, null=True)),
                ('heavy_fighter', models.IntegerField(default=0, null=True)),
                ('cruiser', models.IntegerField(default=0, null=True)),
                ('battleship', models.IntegerField(default=0, null=True)),
                ('interceptor', models.IntegerField(default=0, null=True)),
                ('bomber', models.IntegerField(default=0, null=True)),
                ('destroyer', models.IntegerField(default=0, null=True)),
                ('deathstar', models.IntegerField(default=0, null=True)),
                ('reaper', models.IntegerField(default=0, null=True)),
                ('explorer', models.IntegerField(default=0, null=True)),
                ('espionage_probe', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('blocked', models.BooleanField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('token', models.CharField(max_length=50, null=True)),
                ('auth', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Celestial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordintate', models.CharField(max_length=30)),
                ('universum', models.CharField(max_length=30, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('metal', models.CharField(max_length=30, null=True)),
                ('crystal', models.CharField(max_length=30, null=True)),
                ('deuterium', models.CharField(max_length=30, null=True)),
                ('energy', models.CharField(max_length=30, null=True)),
                ('buildings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyogame.buildings')),
                ('defences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyogame.defences')),
                ('ships', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyogame.ships')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universum', models.CharField(max_length=30, null=True)),
                ('repeat', models.IntegerField(null=True)),
                ('nextRepeat', models.DateTimeField(null=True)),
                ('active', models.BooleanField(null=True)),
                ('base', models.CharField(max_length=20, null=True)),
                ('saiver', models.BooleanField(null=True)),
                ('expedition', models.BooleanField(null=True)),
                ('collector', models.BooleanField(null=True)),
                ('collectorTime', models.TimeField(null=True)),
                ('raider', models.BooleanField(null=True)),
                ('builder', models.BooleanField(null=True)),
                ('builderDefences', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyogame.defences')),
                ('builderFleet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='builderFleet', to='pyogame.ships')),
                ('expeditionFleet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expeditionFleet', to='pyogame.ships')),
                ('raiderFleet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raiderFleet', to='pyogame.ships')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BotLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
